#!/bin/bash
set -ex

for target in base odoo; do

    # Don't build base if BUILD_TAG_BASE != true
    if [ "$target" == "base" ] && [ -z "$BUILD_TAG_BASE" ]; then
        continue
    fi

    docker image build \
        --file "$DOCKERFILE_PATH" \
        --build-arg VCS_REF="$GIT_SHA1" \
        --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
        --build-arg ODOO_VERSION="$DOCKER_TAG" \
        --build-arg ODOO_SOURCE="${ODOO_SOURCE-odoo/odoo}" \
        --build-arg ODOO_SOURCE_DEPTH="${ODOO_SOURCE_DEPTH-1}" \
        --build-arg GITHUB_USER="$GITHUB_USER" \
        --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" \
        --tag "$TAG" \
        --target $target \
        .

done
