#!/bin/bash
set -ex

for target in base odoo; do

    # Don't build base if BUILD_TAG_BASE != true
    if [ "$target" == "base" ] && [ -z "$BUILD_TAG_BASE" ]; then
        continue
    fi

    docker push "$TAG"

done
